configs:
  outputPath: "[path to your output directory]"
  calibration:
    chessboardDims: [8, 5] # If you have a 9x6 chessboard
    chessboardSquareSize: 48 # in mm
  elp:
    imageSize: [640, 480]
    ports:
      lCam: "/dev/video4"
      rCam: "/dev/video6"
